coverage:
  round: down
  range: 55..100
  precision: 2
  status:
    patch: no
  ignore:
  - 'internal/server/mock/*'
  - 'internal/server/handler/protometrics/*'
  - 'internal/agent/generated/protoagent/*'
  - 'internal/agent/generated/mocks/*'
  - 'gen/*'
  - 'gen/proto/internal/server/handler/protometrics/*'